version: '3'
services:
  elasticsearch:
    image: elasticsearch:8.8.0
    ports:
      - 9920:9200
      - 9930:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false